print('*********************************')
print('Tugas 1 Sistem Operasi Kelas-B')
print('*********************************')
print('Nama: Daffania Iffat Laurensyah')
print('NPM : 21083010123')
print('*********************************')
print('notes:')
print('*********************************')
print('Halo dunia!')
print('ini adalah skrip Bash pertamaku di Linux')
